name: webview_bridge
description: "跨项目复用的 WebView + JSBridge 能力插件（分发层 + 能力层 + 宿主/UI 适配层）。"
version: 0.0.2
publish_to: http://s4.qbuild.corp.qihoo.net:4000
homepage: https://github.com/haofeibiao1-stack/webview
repository: https://github.com/haofeibiao1-stack/webview.git

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.0.0
  share_plus: ^12.0.0
  image_gallery_saver_plus: ^4.0.0
  http: ^1.2.2
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
